kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-pvc
  labels:
    app: local-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
     storage: 500M
  storageClassName: local-storage

