---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: demo-pv
  namespace: demo
  labels:
    app: mysql
    owner: cloudEnthusisatic
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /tmp/demo1

