---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-pvc
  labels:
    app: mysql
    owner: cloudEnthusiastic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
