---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: nginx
  name: nginx-deployment
  labels:
    app: nginx
    env: production
    owner: cloudEnthusiastic
spec:
  replicas: 3
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      name: nginx-deployment
      labels:
        env: production
        app: nginx
    spec:
      containers:
        - name: nginx-deployment
          image: nginx
          ports:
            - containerPort: 80


