---
kind: ReplicaSet
apiVersion: apps/v1
metadata:
  namespace: nginx
  name: nginx-replicaset
  labels:
    owner: cloudEnthusiastic
    env: production
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      env: production
  template:
    metadata:
      name: nginx-replicaset
      labels:
        env: production
    spec:
      containers:
        - name: nginx-replicaset
          image: nginx
          ports:
            - containerPort: 80
