---
kind: Service
apiVersion: v1
metadata:
  namespace: mysql
  name: mysql-service
  labels:
    owner: cloudEnthusiastic
    env: production
    app: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
