---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-pv
  namespace: nginx
  labels:
    owner: cloudEnthusiastic
    app: nginx
    env: production
spec:
  storageClassName: local-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/data
  persistentVolumeReclaimPolicy: Delete

