---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  namespace: todo-app
  labels:
    owner: cloudEnthusiastic
    app: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      name: todo-app
      labels:
        owner: cloudEnthusiastic
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: cloudenthusiastic/todo-app
          ports:
            - containerPort: 80
          imagePullPolicy: Always
      imagePullSecrets:
        - name: cloudenthusiastic-registry-secret

